name: pytket-custatevec-test
channels:
  - cqcl
  - conda-forge
dependencies:
  # Conda packages
  - python
  - pip
  - pytket
  - cupy
  - cuquantum-python
  - pytest

  # Pip-only packages
  - pip:
      - pytket-qiskit
      - pytket-qulacs
      - mypy